project_id = "wpvhlrsehnxwetjwolhd"

[functions.create-order]
verify_jwt = false

[functions.check-low-stock]
verify_jwt = false

[functions.setup-courier-accounts]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = true
